backend:
  name: git-gateway
  branch: main
collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
